window.translations = {
    en: {
        welcome_title: "Welcome! 🐦‍⬛",
        welcome_text: "Hello there! Thank you for exploring and showing interest in <b>birdWatch</b>. This is a personal project lovingly crafted for my girlfriend to encourage our outdoor adventures, aiming to support one of her fondest hobbies: <b>birdwatching</b>. I genuinely hope this platform enriches your own birding experiences as well. If you have any suggestions, please feel free to drop me a message. <br> <br> <b>Happy birding!</b>",
        welcome_btn: "Got it!",
        login_title: "BirdWatch",
        login_desc: "Welcome to your personal bird journal.",
        login_btn: "Log in with Google",
        pending_title: "Awaiting Approval",
        pending_desc: "Your account needs Admin approval to access the map.",
        logout_pending_btn: "Log out",
        
        menu_species: "Scrapbook",
        menu_achievements: "Achievements",
        menu_profile: "My Profile",
        menu_about: "About it",
        menu_suggestions: "Suggestions",
        menu_logout: "Logout",
        footer_music: "Music by",

        add_record_btn: "➕ Add a record",

        modal_record_title: "Record a Discovery",
        modal_edit_title: "Edit Discovery",
        photo_btn: "Select Photo (Max 10MB)",
        ph_location: "Location (Auto-filled)",
        ph_date: "Date & Time (Auto-extracted)",
        ph_equip: "Equipment (e.g. Binoculars, Nikon)",
        ph_informal: "Informal Name (e.g. Robin)",
        ph_scientific: "Scientific Name",
        btn_save: "Save Discovery",
        btn_saving: "Saving...",
        btn_cancel: "Cancel",
        btn_update_loc: "📍 Update Location",

        modal_crop_title: "Adjust Photo",
        btn_confirm_crop: "Confirm Crop",

        modal_species_title: "My Scrapbook",
        btn_close: "Close",
        btn_edit: "✏️ Edit",
        btn_delete: "🗑️ Delete",
        btn_zoom: "🎯 Zoom to",
        filter_all: "All countries",
        search_placeholder: "Search by name...",
        
        modal_achievements_title: "My Achievements 🏆",
        achievements_desc: "Register species in different regions to conquer achievements!",
        completed: "Completed",

        modal_profile_title: "Your Explorer Stats",
        stat_total: "Total Birds",
        stat_countries: "Regions Explored",
        stat_conquered: "Conquered (10+)",
        chart_label: "Birds per Region",

        loading_loc: "Loading location...",
        loading: "Loading...",
        unknown_loc: "Unknown Location",
        unknown_country: "Unknown Country",
        default_bird: "Bird",
        no_species: "No species found yet. Start exploring!",
        no_achievements: "No achievements yet. Add your first record!",
        confirm_delete: "Are you sure you want to delete this discovery?",
        err_large_file: "File is larger than 10MB!",
        err_saving: "Error saving data.",
        alert_blocked_audio: "Waiting for user interaction to play music.",
        gps_error: "Could not access GPS. Please check if your browser has Location permissions enabled in your device settings.",
        click_map_loc: "Click anywhere on the map to set a new location."
    },
    pt: {
        welcome_title: "Bem-vindo! 🐦‍⬛",
        welcome_text: "Olá! Obrigado por explorar e demonstrar interesse no <b>birdWatch</b>. Este é um projeto pessoal feito com muito carinho para minha namorada, para incentivar nossas aventuras ao ar livre e apoiar um de seus hobbies favoritos: <b>birdwatching</b> (observação de aves). Espero sinceramente que esta plataforma enriqueça suas próprias experiências também. Se tiver sugestões, fique à vontade para me enviar uma mensagem. <br> <br> <b>Boas observações!</b>",
        welcome_btn: "Entendi!",
        login_title: "BirdWatch",
        login_desc: "Bem-vindo ao seu diário pessoal de aves.",
        login_btn: "Entrar com o Google",
        pending_title: "Aguardando Aprovação",
        pending_desc: "Sua conta precisa da aprovação do Admin para acessar o mapa.",
        logout_pending_btn: "Sair",
        
        menu_species: "Álbum",
        menu_achievements: "Conquistas",
        menu_profile: "Meu Perfil",
        menu_about: "Sobre o projeto",
        menu_suggestions: "Sugestões",
        menu_logout: "Sair",
        footer_music: "Música por",

        add_record_btn: "➕ Adicionar registro",

        modal_record_title: "Registrar Descoberta",
        modal_edit_title: "Editar Descoberta",
        photo_btn: "Escolher Foto (Máx 10MB)",
        ph_location: "Localização (Automática)",
        ph_date: "Data e Hora (Automática)",
        ph_equip: "Equipamento (ex: Binóculos, Nikon)",
        ph_informal: "Nome Comum (ex: Sabiá)",
        ph_scientific: "Nome Científico",
        btn_save: "Salvar Descoberta",
        btn_saving: "Salvando...",
        btn_cancel: "Cancelar",
        btn_update_loc: "📍 Atualizar Localização",

        modal_crop_title: "Ajustar Foto",
        btn_confirm_crop: "Confirmar Corte",

        modal_species_title: "Meu Álbum",
        btn_close: "Fechar",
        btn_edit: "✏️ Editar",
        btn_delete: "🗑️ Deletar",
        btn_zoom: "🎯 Ir para",
        filter_all: "Todos os países",
        search_placeholder: "Buscar por nome...",
        
        modal_achievements_title: "Minhas Conquistas 🏆",
        achievements_desc: "Registre espécies nas regiões para desbloquear conquistas!",
        completed: "Concluído",

        modal_profile_title: "Suas Estatísticas",
        stat_total: "Total de Aves",
        stat_countries: "Regiões Exploradas",
        stat_conquered: "Conquistados (10+)",
        chart_label: "Aves por Região",

        loading_loc: "Carregando localização...",
        loading: "Carregando...",
        unknown_loc: "Local Desconhecido",
        unknown_country: "País Desconhecido",
        default_bird: "Ave",
        no_species: "Nenhuma espécie encontrada ainda. Comece a explorar!",
        no_achievements: "Nenhuma conquista ainda. Adicione seu primeiro registro!",
        confirm_delete: "Tem certeza de que deseja deletar esta descoberta?",
        err_large_file: "O arquivo é maior que 10MB!",
        err_saving: "Erro ao salvar os dados.",
        alert_blocked_audio: "Aguardando interação do usuário para tocar música.",
        gps_error: "Não foi possível acessar o GPS. Verifique nos Ajustes do celular se o seu navegador tem permissão de Localização.",
        click_map_loc: "Clique em qualquer lugar do mapa para definir a nova localização."
    },
    es: {
        welcome_title: "¡Bienvenido! 🐦‍⬛",
        welcome_text: "¡Hola! Gracias por explorar y mostrar interés en <b>birdWatch</b>. Este es un proyecto personal creado con mucho cariño para mi novia, para fomentar nuestras aventuras al aire libre y apoyar uno de sus pasatiempos favoritos: <b>birdwatching</b> (observación de aves). Espero sinceramente que esta plataforma también enriquezca tus propias experiencias. Si tienes alguna sugerencia, no dudes en enviarme un mensaje. <br> <br> <b>¡Feliz observación!</b>",
        welcome_btn: "¡Entendido!",
        login_title: "BirdWatch",
        login_desc: "Bienvenido a tu diario personal de aves.",
        login_btn: "Iniciar sesión con Google",
        pending_title: "Esperando Aprobación",
        pending_desc: "Tu cuenta necesita la aprobación del Administrador para acceder al mapa.",
        logout_pending_btn: "Cerrar sesión",
        
        menu_species: "Álbum",
        menu_achievements: "Logros",
        menu_profile: "Mi Perfil",
        menu_about: "Sobre el proyecto",
        menu_suggestions: "Sugerencias",
        menu_logout: "Cerrar sesión",
        footer_music: "Música de",

        add_record_btn: "➕ Añadir registro",

        modal_record_title: "Registrar Descubrimiento",
        modal_edit_title: "Editar Descubrimiento",
        photo_btn: "Elegir Foto (Máx 10MB)",
        ph_location: "Ubicación (Automática)",
        ph_date: "Fecha y Hora (Automática)",
        ph_equip: "Equipo (ej: Prismáticos, Nikon)",
        ph_informal: "Nombre Común (ej: Mirlo)",
        ph_scientific: "Nombre Científico",
        btn_save: "Guardar Descubrimiento",
        btn_saving: "Guardando...",
        btn_cancel: "Cancelar",
        btn_update_loc: "📍 Actualizar Ubicación",

        modal_crop_title: "Ajustar Foto",
        btn_confirm_crop: "Confirmar Recorte",

        modal_species_title: "Mi Álbum",
        btn_close: "Cerrar",
        btn_edit: "✏️ Editar",
        btn_delete: "🗑️ Eliminar",
        btn_zoom: "🎯 Ir a",
        filter_all: "Todos los países",
        search_placeholder: "Buscar por nombre...",
        
        modal_achievements_title: "Mis Logros 🏆",
        achievements_desc: "¡Registra especies en las regiones para desbloquear logros!",
        completed: "Completado",

        modal_profile_title: "Tus Estadísticas",
        stat_total: "Total de Aves",
        stat_countries: "Regiones Exploradas",
        stat_conquered: "Conquistados (10+)",
        chart_label: "Aves por Región",

        loading_loc: "Cargando ubicación...",
        loading: "Cargando...",
        unknown_loc: "Ubicación Desconocida",
        unknown_country: "País Desconocido",
        default_bird: "Ave",
        no_species: "Aún no hay especies. ¡Empieza a explorar!",
        no_achievements: "Aún no hay logros. ¡Añade tu primer registro!",
        confirm_delete: "¿Estás seguro de que deseas eliminar este descubrimiento?",
        err_large_file: "¡El archivo es mayor de 10MB!",
        err_saving: "Error al guardar los datos.",
        alert_blocked_audio: "Esperando interacción del usuario para reproducir música.",
        gps_error: "No se pudo acceder al GPS. Verifique en la configuración de su dispositivo si su navegador tiene permisos de Ubicación.",
        click_map_loc: "Haz clic en cualquier lugar del mapa para establecer una nueva ubicación."
    }
};
